### ISSUE TITLE
CI doesn't accurately test everything

### ISSUE THREAD

**Issue by dissolve** [microformats/microformats-ruby#101]
version 4.0.8 was able to be released and passed all CI tests, but it failed when testing on  a different system as 'require "set"' was not in the code base... why do all tests pass despite this??

**Comment by jgarber623** [comment]
Can you provide some extra system details? I just installed v4.0.8 on macOS 10.13.6 (`gem install microformats -v 4.0.8`) and was able to successfully use the CLI:

```sh
microformats https://sixtwothree.org
```

…without any errors.

**Comment by dissolve** [comment]
The error I got was an uninitialized constant on format_parser:10 (going of
of memory). This was the line that first used Set::. This was fixed by
adding require 'set'.  I don't know why this worked on some machines and
not on others however.

I will have to look in to it closer

**Comment by jgarber623** [comment]
Okay, so after asking around, I think the problem breaks down to a misunderstanding on my part of the Ruby "core" vs. the "standard library."

- https://ruby-doc.org/core-2.4.4
- https://ruby-doc.org/stdlib-2.4.4

`Set` is part of the standard library and would need to be included using `require 'set'` as you've done. Apologies on my part for having possibly introduced that problem.

That _might_ be the resolution to this issue.

**Comment by dissolve** [comment]
Well it solved the issue, that's exactly what I did for 4.0.9.
The real issue here is that the CI server and my dev server (ubuntu) automatically included the standard libraries, while my personal machine (gentoo) after deploy did not.  The goal is for the CI environment to be more strict and not auto-include standard libs as obviously not all systems do that.

**Comment by dissolve** [comment]
i think this can be closed now?

**Comment by jgarber623** [comment]
> i think this can be closed now?

@dissolve Yep, closing!
