### ISSUE TITLE
Update gem for Ruby 3.0 support

### ISSUE THREAD

**Issue by shleeable** [microformats/microformats-ruby#119]
Hey, thanks for merging in the change. I figure it needs testing, but just keeping this ticket open to keep an eye on the update.

https://rubygems.org/gems/microformats

**Comment by ClearlyClaire** [comment]
@dissolve would it be possible to release a new microformats-ruby version with the mentioned changes?

**Comment by dissolve** [comment]
I am testing it out locally now, I am on 3.0 on my local and not able to build for some odd reason which gives me a little pause to release it just yet.  I'll try and get this figured out very soon and have it out in the next day or two

**Comment by dissolve** [comment]
bundle install
Fetching gem metadata from https://rubygems.org/...........
Resolving dependencies...
listen-3.2.1 requires ruby version >= 2.2.7, ~> 2.2, which is incompatible with
the current version, ruby 3.0.0p0

upping in to listen-3.5.1 in the gem.lock file seems to fix it for 3.0.0 on my machine
Anyone see any issues with that?

**Comment by dissolve** [comment]
aaand i immediately realize that Gemfile.lock isn't in the repo.  I've been in composer and npm land too long

**Comment by dissolve** [comment]
version 4.3.1 is released, closing this before I make myself look more foolish

**Comment by shleeable** [comment]
Thanks @dissolve
